csrc/type_shim.h
setup.py

This PR enables Apex support on rocm and the following changes have been applied.
1. Hipify the cuda files. 
2. Base framework for enabling CUDAExtensions on ROCm.
3. Enable MultiTensorApply extension.

Enable Apex on ROCm and support multi tensor support.

---

apex/contrib/csrc/optimizers/fused_adam_cuda_kernel.cu
apex/contrib/csrc/xentropy/xentropy_kernel.cu
apex/contrib/multihead_attn/self_multihead_attn_func.py
apex/mlp/mlp.py
csrc/mlp.cpp
csrc/mlp_cuda.cu
csrc/multi_tensor_axpby_kernel.cu
csrc/multi_tensor_l2norm_kernel.cu
csrc/multi_tensor_lamb.cu
csrc/multi_tensor_scale_kernel.cu
tests/L0/run_mlp/test_mlp.py

Integrate changes from upstream

[Upstream] IFU 05072020

---

csrc/layer_norm_cuda_kernel.cu
setup.py

1. Updates the setup script to run layernorm extension on rocm.
2. Necessary changes needed to run on ROCm fork.

Enable FusedLayernorm extension.

---

setup.py

Otherwise, `version_dependent_macros` are left off during compile.

Fix compile args, adding version_dependent_macros.

---

.jenkins/docker/build.sh
.jenkins/docker/launch.sh
Dockerfile
apex/__init__.py
apex/testing/__init__.py
apex/testing/common_utils.py
tests/L0/common_utils.py
tests/L0/run_amp/test_basic_casts.py
tests/L0/run_amp/test_checkpointing.py
tests/L0/run_amp/test_fused_sgd.py
tests/L0/run_amp/test_multi_tensor_axpby.py
tests/L0/run_amp/test_multi_tensor_l2norm.py
tests/L0/run_amp/test_multiple_models_optimizers_losses.py
tests/L0/run_amp/test_rnn.py
tests/L0/run_test.py

This PR enables the following things:
1. Creates an utiltity to run tests on ROCm - skipIfRocm, TEST_WITH_ROCM.
2. Created a blacklist of ROCm tests that are not enabled yet or which are not applicable to rocm.
3. Enable tests -> run_amp, run_optimizers, run_fp16util.

[Test] Enable base test framework

---

apex/contrib/csrc/optimizers/fused_adam_cuda_kernel.cu
apex/contrib/csrc/optimizers/fused_lamb_cuda_kernel.cu
csrc/multi_tensor_adagrad.cu
csrc/multi_tensor_adam.cu
csrc/multi_tensor_apply.cuh
csrc/multi_tensor_axpby_kernel.cu
csrc/multi_tensor_l2norm_kernel.cu
csrc/multi_tensor_lamb.cu
csrc/multi_tensor_lamb_stage_1.cu
csrc/multi_tensor_lamb_stage_2.cu
csrc/multi_tensor_novograd.cu
csrc/multi_tensor_scale_kernel.cu
csrc/multi_tensor_sgd_kernel.cu

This works around a known performance issue.  When a real fix becomes available, we can revert this.

pass all TensorListMetadata as pointer to pinned host memory

---

csrc/multi_tensor_l2norm_kernel.cu

This PR sets launch bound for cleanup(...) kernel to 1024 because of the assumption of the number of threads in the kernel to be greater than default launch bounds on ROCm

Fix launch bounds for cleanup(...) call

---

csrc/layer_norm_cuda_kernel.cu
tests/L0/run_test.py

This PR adds a fix to use the correct warp size for WARP_SHFL* macros in layernorm kernels. Also, enables the LayerNorm unit tests on ROCm

Fix LayerNorm op on ROCm

---

csrc/type_shim.h
tests/L0/run_amp/test_multi_tensor_l2norm.py

This PR fixes the warp size for ROCm in the reduce_block_into_lanes function.  It uses the warpSize variable to compute the reduction scope instead of using the fixed warp size of 32.  Since this function is used by multi_tensor_l2norm, this PR should also fix the correctness of multi_tensor_l2norm.

Fix reduce_block_into_lanes for multi_tensor_l2norm for ROCm

---

setup.py

String comparison messes up in cases such as `torch.__version__ = 1.10.blah`

Make torch version check numeric

---

apex/contrib/csrc/groupbn/batch_norm.cu
apex/contrib/csrc/groupbn/batch_norm.h
apex/contrib/csrc/groupbn/batch_norm_add_relu.cu
apex/contrib/csrc/groupbn/batch_norm_add_relu.h
apex/contrib/csrc/groupbn/cuda_utils.h
apex/contrib/csrc/groupbn/dnn.h
apex/contrib/csrc/groupbn/nhwc_batch_norm_kernel.h
apex/contrib/groupbn/batch_norm.py
apex/contrib/test/groupbn/test_groupbn.py
setup.py

Enable NHWC group batch norm on a single GPU on ROCm (bn_group = 1).  The
multi-GPU case (bn_group > 1) will be revisited in the future.
The following are the main changes:
1) Use MIOpen data structures/functions for HIP instead of CUDNN
2) For the warp-level primitive code for HIP, we ensure that the code operates
on 64-thread wide warp instead of 32-thread wide
3) Disable all the bn_group > 1 paths for HIP
4) Make all data pointers contiguous to support non-contiguous input tensors
5) Use 64-bit ReLU bitmask for HIP
6) For fusion kernels, rectify the output data if it is less than or equal to
zero to improve stability of the kernels
Notes:
1) Multi-stream is not tested.
2) We have not optimized for performance

Enable group batch norm (--bnp) on ROCm (only bn_group = 1)

---

setup.py

Instead of specifying a separate flag for each extension, we can just override the --cuda_ext flag to enable building all supported extensions.
This also implies that any new apex extensions enabled in the future would require a setup.py update to be built when --cuda_ext is specified.

Enable all supported CUDA extensions using --cuda_ext flag

---

tests/L0/run_amp/test_basic_casts.py
tests/L0/run_amp/test_cache.py
tests/L0/run_amp/test_checkpointing.py
tests/L0/run_amp/test_rnn.py
tests/L0/run_optimizers/test_fused_optimizer.py

The failing unit tests introduced by the new PyTorch commits related to "if cached_x.grad_fn.next_functions[1][0].variable is not x: IndexError: tuple index out of range" also observed on CUDA (upstream). We will first skip the following unit tests and re-enable them later.
- test_conv2d_is_half (test_basic_casts.TestBasicCastsHalf)
- test_linear_is_half (test_basic_casts.TestBasicCastsHalf)
- test_whitelist_module_fp32_weight (test_cache.TestCache)
- test_restoring (test_checkpointing.TestCheckpointing)
- test_state_dict (test_checkpointing.TestCheckpointing)
- test_gru_cell_is_half (test_rnn.TestRnnCells)
- test_lstm_cell_is_half (test_rnn.TestRnnCells)
- test_rnn_cell_is_half (test_rnn.TestRnnCells)
Additionally, the failing test for test_half (test_fused_optimizer.TestFusedAdam) is …

Skip failing unit tests

---

apex/contrib/groupbn/batch_norm.py

This patch converts torch.cuda.LongTensor's argument of bn_addrelu's
bitmask to int to fix the type error.

Fix bn_addrelu's bitmask type error

---

apex/contrib/csrc/fmha/src/fmha.h
apex/contrib/csrc/multihead_attn/dropout.h
apex/contrib/csrc/multihead_attn/softmax.h
apex/contrib/csrc/transducer/transducer_joint_kernel.cu
setup.py

This fixes Apex build issues with older PyTorch versions 1.8.1, 1.9 and 1.10, since they didn't have the `ATen/cuda/CUDAGeneratorImpl.h` file available.
```
15:05:31  [0m[91m    In file included from /tmp/pip-req-build-sttueip5/apex/contrib/csrc/multihead_attn/additive_masked_softmax_dropout_hip.hip:15:
15:05:31      /tmp/pip-req-build-sttueip5/apex/contrib/csrc/multihead_attn/dropout_hip.h:8:10: fatal error: 'ATen/hip/HIPGeneratorImpl.h' file not found
15:05:31      #include <ATen/hip/HIPGeneratorImpl.h>
```

Cherry-pick b2fdf9c from upstream Apex and resolve conflicts

---

apex/contrib/csrc/groupbn/batch_norm.cu
apex/contrib/csrc/groupbn/batch_norm_add_relu.cu
apex/contrib/groupbn/batch_norm.py
apex/contrib/test/groupbn/test_groupbn_channel_last.py

Group Batch Norm (GBN) is an NHWC operation.  It assumes that the
underlying memory format of an input tensor is NHWC.  It originally does
not support PyTorch's memory_format API.
To support PyTorch's memory_format API, i.e., .to(memory_format=...) or
.contiguous(memory_format=...), we add the torch_channels_last
flag to indicate whether the workload adopts the PyTorch memory_format
API by setting memory_format=torch.channels_last.  This flag allows GBN
to handle memory formats of input tensors properly.
An example to use memory_format in GBN:
"""
from apex.contrib.groupbn.batch_norm import BatchNorm2d_NHWC
GBN = BatchNorm2d_NHWC(planes, fuse_relu=True, bn_group=1, torch_channels_last=True)
"""
The cases that GBN handles are as follows:
1. torch_channels_last=True and input tensor's …

Added support for memory format API(torch.channels_last) in GBN

---

apex/contrib/csrc/multihead_attn/encdec_multihead_attn_cuda.cu
apex/contrib/csrc/multihead_attn/encdec_multihead_attn_norm_add_cuda.cu
apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_additive_mask_cuda.cu
apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_cuda.cu
apex/contrib/csrc/multihead_attn/self_multihead_attn_cuda.cu
apex/contrib/csrc/multihead_attn/self_multihead_attn_norm_add_cuda.cu
csrc/mlp_cuda.cu
setup.py

As [the PR](https://github.com/pytorch/pytorch/pull/71881/files) in PyTorch upstream for rocblas_gemm_flags_fp16_alt_impl (used in Apex MHA and MLP extensions) has renamed BackwardPassGuard to ROCmBackwardPassGuard, the changes in this PR can prevent the backward-breaking issues.

Make rocblas_gemm_flags_fp16_alt_impl backward-compat for new naming

---

apex/normalization/__init__.py
apex/normalization/fused_layer_norm.py
csrc/layer_norm_cuda.cpp
csrc/layer_norm_cuda_kernel.cu
docs/source/layernorm.rst
tests/L0/run_fused_layer_norm/test_fused_layer_norm.py

There are two introduced unit test failures from `tests/L0/run_fused_layer_norm/test_fused_layer_norm.py`.
```
========================================================================= short test summary info ==========================================================================
FAILED test_fused_layer_norm.py::TestFusedLayerNormElemWiseHalf::test_layer_norm - RuntimeError: expected scalar type Float but found Half
FAILED test_fused_layer_norm.py::TestFusedLayerNormElemWiseBFloat16::test_layer_norm - RuntimeError: expected scalar type Float but found BFloat16
================================================================= 2 failed, 15 passed, 3 skipped in 42.61s =================================================================
```

Enable FusedRMSNorm

---

tests/L0/run_optimizers/test_fused_optimizer.py
tests/L0/run_optimizers/test_lamb.py

FusedRMSNorm PR: https://github.com/ROCmSoftwarePlatform/apex/pull/78
The failed unit tests which were skipped in this PR: https://github.com/ROCmSoftwarePlatform/apex/pull/78#issuecomment-1201839061

Skip the failing unit tests from the FusedRMSNorm PR

---

apex/amp/utils.py
tests/L0/run_amp/test_basic_casts.py
tests/L0/run_amp/test_cache.py
tests/L0/run_amp/test_checkpointing.py
tests/L0/run_amp/test_rnn.py

- Cherry-picked the fix from upstream: https://github.com/NVIDIA/apex/pull/1282/commits/01802f623c9b54199566871b49f94b2d07c3f047
- Un-skipped the related unit tests which were raised in https://github.com/ROCmSoftwarePlatform/apex/issues/62
We can close the issue once this PR has been merged.

cached cast fix

---

apex/contrib/bottleneck/halo_exchangers.py
apex/contrib/csrc/nccl_p2p/nccl_p2p_cuda.cu
apex/contrib/csrc/peer_memory/peer_memory_cuda.cu
apex/contrib/csrc/peer_memory/peer_memory_cuda.cuh
apex/contrib/peer_memory/__init__.py
apex/contrib/peer_memory/peer_halo_exchange_module_tests.py
apex/contrib/peer_memory/peer_halo_exchanger_1d.py
setup.py

These extensions are needed to enable the fast_bottleneck Apex extension. While there are no unit tests for these extensions, there is a test file `peer_halo_exchange_module_tests.py` added for the --peer_memory extension. The tests in that file pass on CUDA but fail inconsistently on ROCm.

Enable --peer_memory and --nccl p2p extensions for ROCm

---

setup.py

Build Apex with the original setup.py (with and without ninja for `gfx900;gfx906;gfx908;gfx90a;gfx1030`) on a system with the default MAX_JOBS=32 with the following two commands:
**1. pip install**
```
time pip install --disable-pip-version-check --global-option="--cpp_ext" --global-option="--cuda_ext" -v . 
```
**2. python setup.py install**
```
time python setup.py install --cpp_ext --cuda_ext
```
The extensions built in the experiment:
| Extension Name          | Support on ROCm |
|-------------------------|-----------------|
| --cpp_ext               | Yes             |
| --distributed_adam      | Yes             |
| --distributed_lamb      | Yes             |
| --cuda_ext              | Yes             |
| --permutation_search    | **No**          |
| --bnp                   | Yes …

Faster build

---

apex/contrib/csrc/index_mul_2d/index_mul_2d_cuda_kernel.cu
setup.py

ATen/cuda/Atomic.cuh does not exist before Pytorch 1.11. Therefore, this PR is to make index_mul_2d extension compatible with various Pytorch releases.
- New Pytorch releases (after 1.11): #include <ATen/cuda/Atomic.cuh>
- Old Pytorch releases (before 1.11): #include <THC/THCAtomics.cuh>

Make index_mul_2d extension backward compatible for Atomic header include

---

apex/optimizers/fused_sgd.py
tests/L0/run_optimizers/test_fused_optimizer_channels_last.py

Authored by @luise1030 to address the issue of tensor memory type inconsistency on Resnet50 trained with NHWC format.
To run the corresponding unit tests for the code changes in this PR:
$ python tests/L0/run_test.py --include run_optimizers
```
test_float (test_fused_optimizer.TestFusedSGD) ... ok
test_half (test_fused_optimizer.TestFusedSGD) ... ok
test_multi_device (test_fused_optimizer.TestFusedSGD) ... ok
```
Internal JIRA ticket for the context: https://ontrack-internal.amd.com/browse/SWDEV-357815

Consider both contiguous and channels_last tensors for FusedSGD

---

tests/L0/run_amp/test_checkpointing.py
tests/L0/run_optimizers/test_fused_optimizer.py

As the regression has been resolved from PyTorch 1.12.1 and above, the skipped unit tests related to https://github.com/ROCmSoftwarePlatform/apex/issues/82 can be unskipped.
test_adam_option (test_fused_optimizer.TestFusedAdam): due to https://github.com/pytorch/pytorch/issues/80809#issuecomment-1175211598
test_multi_device (test_fused_optimizer.TestFusedAdam): due to https://github.com/pytorch/pytorch/issues/80809#issuecomment-1175211598
test_float (test_fused_optimizer.TestFusedAdam): due to https://github.com/pytorch/pytorch/issues/80809#issuecomment-1175211598
test_bfloat16 (test_fused_optimizer.TestFusedAdam): due to https://github.com/pytorch/pytorch/issues/80809#issuecomment-1175211598
In addition, `test_state_dict (test_checkpointing.TestCheckpointing)` failed because of the …

Unskip some unit tests related to issue #82

---

apex/contrib/test/run_rocm_extensions.py
csrc/fused_dense.cpp

With Kk's help, we found a bug in fused_dense_cuda on ROCm.  
It failed the unit test of fused_dense on ROCm before this fix. 
Steps to reproduce:
$ cd apex/contrib/test/fused_dense
$ pytest test_fused_dense.py

Fix a bug in fused_dense_cuda on ROCm

---

apex/contrib/csrc/peer_memory/peer_memory_cuda.cu

The keyword 'register' for storage class is removed in C++17, so keeping it active for only c++14 and lower.
Update pytorch build with C++17 support and all extensions build too.

Update register keyword handling for C++17

---

apex/multi_tensor_apply/__init__.py
apex/optimizers/fused_lamb.py
apex/optimizers/fused_mixed_precision_lamb.py
csrc/multi_tensor_adam.cu
csrc/multi_tensor_apply.cuh
csrc/multi_tensor_apply_base.cuh
csrc/multi_tensor_axpby_kernel.cu
csrc/multi_tensor_l2norm_kernel.cu
csrc/multi_tensor_l2norm_kernel_mp.cu
csrc/multi_tensor_l2norm_scale_kernel.cu
csrc/multi_tensor_lamb.cu
csrc/multi_tensor_lamb_mp.cu
csrc/multi_tensor_lamb_stage_1.cu
csrc/multi_tensor_lamb_stage_2.cu
csrc/multi_tensor_novograd.cu
csrc/multi_tensor_scale_kernel.cu
csrc/multi_tensor_sgd_kernel.cu
tests/L0/run_optimizers/test_fused_optimizer.py

This change only affects the optimizers specifically when multi_tensor_apply is emabled using --cuda_ext extension when installing apex.
Updating chunk_size to 256 * 32 (8K) which was previously 2048 * 32 (64K).
In addition, updating depth_to_max_blocks to 2560 (8x compared to previous 320).
The performance improvement observed is upto 1.4x for large number of elements, upto 5.2x for moderate number of elements and upto 1.44x for small number of elements.
The set of performance along with comparison with Torch is captured here
https://amdcloud.sharepoint.com/:x:/r/sites/MLSEPerfTeam/Shared%20Documents/Strategic%20Leadership%20Optimizations%20Team%20(SLOT)/Projects/Grid%20Optimization/Elementwise%20Kernel%20-%20Grid%20Optimization%20-%20Benchmark%20sweep.xlsx?d=wa8bacf65a2904002bf3cad4c5776 …

Grid optimization - Chunk_Size optimization.

---

apex/RNN/RNNBackend.py
apex/RNN/cells.py
apex/amp/_amp_state.py
apex/amp/_initialize.py
apex/amp/compat.py
apex/contrib/clip_grad/clip_grad.py
apex/contrib/layer_norm/layer_norm.py
apex/contrib/multihead_attn/encdec_multihead_attn.py
apex/contrib/multihead_attn/self_multihead_attn.py
apex/contrib/sparsity/sparse_masklib.py
apex/fused_dense/fused_dense.py
apex/normalization/fused_layer_norm.py

This PR will fix this issue: https://github.com/ROCmSoftwarePlatform/apex/issues/106.
I have tested it on my dev node with rocm-5.4.0 and PyTorch 1.13.0a0+git941769a which means it should be backward compatible with not only PT 2.0 but also the older PT versions (PT 1.13+ at least).

Cherry-picks some commits to replace torch.Tensor and remove dependency on six 

---

README.md
pyproject.toml

- Cherry-pick of https://github.com/NVIDIA/apex/pull/1669
- Needed to build apex with newer pip >= 23.1 using updated flags.
- Some related JIRAs: [SWDEV-406006](https://ontrack-internal.amd.com/browse/SWDEV-406006) and [SWDEV-405889](https://ontrack-internal.amd.com/browse/SWDEV-405889)

Adding pyproject.toml file

---

apex/contrib/csrc/groupbn/batch_norm.h
apex/contrib/csrc/groupbn/batch_norm_add_relu.h
apex/contrib/csrc/groupbn/cuda_utils.h
apex/contrib/csrc/groupbn/dnn.h
apex/contrib/csrc/groupbn/nhwc_batch_norm_kernel.h
apex/contrib/csrc/multihead_attn/encdec_multihead_attn_cuda.cu
apex/contrib/csrc/multihead_attn/encdec_multihead_attn_norm_add_cuda.cu
apex/contrib/csrc/multihead_attn/layer_norm.cuh
apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_additive_mask_cuda.cu
apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_cuda.cu
apex/contrib/csrc/multihead_attn/self_multihead_attn_cuda.cu
apex/contrib/csrc/multihead_attn/self_multihead_attn_norm_add_cuda.cu
apex/contrib/csrc/multihead_attn/softmax.cuh
apex/contrib/csrc/nccl_p2p/nccl_p2p_cuda.cu
apex/contrib/csrc/peer_memory/peer_memory_cuda.cu
apex/contrib/csrc/transducer/transducer_joint_kernel.cu
apex/contrib/csrc/xentropy/xentropy_kernel.cu
csrc/fused_dense.cpp
csrc/fused_dense_cuda.cu
csrc/layer_norm_cuda_kernel.cu
csrc/mlp_cuda.cu
csrc/multi_tensor_apply.cuh
csrc/multi_tensor_apply_base.cuh
csrc/multi_tensor_l2norm_kernel.cu
csrc/type_shim.h
csrc/welford.cu

rename `__HIP_PLATFORM_HCC__` to `USE_ROCM`. We were using the former to mean USE_ROCM as it is used in pytorch. The `-DUSE_ROCM` comes from using the pytorch CUDAExtension class.

remove HCC references

---

tests/distributed/run_rocm_distributed.sh
tests/distributed/synced_batchnorm/two_gpu_test_different_batch_size.py
tests/distributed/synced_batchnorm/two_gpu_unit_test.py
tests/distributed/synced_batchnorm/unit_test.sh

Fixes to Sync batchnorm test scripts. 
Test result:
torchrun --nnodes 1 --nproc-per-node 2  two_gpu_test_different_batch_size.py --apex
[2024-01-18 19:22:08,932] torch.distributed.run: [WARNING]
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
====SBN two gpu with different batches test passed
torchrun --nnodes 1 --nproc-per-node 2  two_gpu_unit_test.py
[2024-01-18 19:43:50,447] torch.distributed.run: [WARNING]
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your …

Batchnorm support

---

csrc/fused_dense_cuda.cu

Change the compute type for the F16 wrapper around cublas GEMMEx. 
The original code had `CUDA_R_32F` but was changed to `CUBLAS_16F` inadvertently during the rocblas->hipblas changes in PyTorch. Hence, the bug was introduced. 
This change will allow the unit test for `test_fused_dense.py` to pass sucessfully. 
```
/opt/rocm/apex/apex/contrib/test/fused_dense# pytest -v 
============================================================================== test session starts ===============================================================================
platform linux -- Python 3.9.19, pytest-7.3.2, pluggy-1.4.0 -- /opt/conda/envs/py_3.9/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/opt/rocm-6.1.0/apex/apex/contrib/test/fused_dense/.hy …
```

change compute type for F16 wrapper around cublas GEMMEx

---

apex/transformer/testing/distributed_test_base.py

Overriding base test class: do not auto destroy PG upon exit.
affects test cases which have parallel test related to transformer

Overriding base test class: do not auto destroy PG upon exit.

---

apex/transformer/tensor_parallel/layers.py
csrc/megatron/fused_bias_swiglu_cuda.cu
tests/L0/run_transformer/test_layers.py

Reduced the tolerance of UT to -4, Auto initilize the maxthreads from hip property, Fix Deprecated warning
https://ontrack-internal.amd.com/browse/SWDEV-474234
https://ontrack-internal.amd.com/projects/SWDEV/issues/SWDEV-474228?filter=myopenissues

Fix for fused gradiant accumulator Unit test failure and also removed constrants from fused_bias_swiglu

---

csrc/megatron/fused_bias_swiglu_cuda.cu
setup.py

Changed the setup.py to read the Environment variable PYTORCH_ROCM_ARCH instead of reading the rocminfo, Also read the maxThreadPerBlock from the HIP property
Fix for bug : https://github.com/ROCm/apex/issues/175

Fix setup.py to read environment varialbe instead of parsing rocminfo 

---

apex/transformer/tensor_parallel/layers.py
csrc/megatron/fused_bias_swiglu_cuda.cu
setup.py
tests/L0/run_transformer/test_layers.py

Reduced the tolerance of UT to -4, Auto initilize the maxthreads from hip property, Fix Deprecated warning
Changed the setup.py to read the Environment variable PYTORCH_ROCM_ARCH instead of reading the rocminfo, Also read the maxThreadPerBlock from the HIP property
Added get device Properly for Forward Function
replacing hip functions with cu
fix issue : https://github.com/ROCm/apex/issues/175

Fix setup.py

---

apex/contrib/csrc/nccl_allocator/NCCLAllocator.cpp
apex/contrib/csrc/nccl_p2p/nccl_version.cpp
apex/contrib/csrc/nccl_p2p/nccl_version_check.cu
apex/contrib/csrc/optimizers/fused_adam_cuda.cpp
apex/contrib/csrc/optimizers/multi_tensor_distopt_adam.cpp
apex/contrib/csrc/optimizers/multi_tensor_distopt_adam_kernel.cu
apex/contrib/nccl_allocator/__init__.py
apex/contrib/nccl_allocator/nccl_allocator.py
apex/contrib/optimizers/distributed_fused_adam.py
apex/contrib/test/optimizers/test_dist_adam.py
csrc/multi_tensor_apply.cuh
setup.py

Ported Distributed_fused_adam from Nvidia/apex.
Ref: https://ontrack-internal.amd.com/browse/SWDEV-519796

Feature distributed fused adam

---

setup.py

add condition to remove nccl_allocator only if it is mentioned explicitly

for distributed fused adam, 

---

apex/contrib/csrc/nccl_allocator/NCCLAllocator.cpp
apex/contrib/csrc/nccl_p2p/nccl_version.cpp
apex/contrib/csrc/nccl_p2p/nccl_version_check.cu
apex/contrib/csrc/optimizers/fused_adam_cuda.cpp
apex/contrib/csrc/optimizers/multi_tensor_distopt_adam.cpp
apex/contrib/csrc/optimizers/multi_tensor_distopt_adam_kernel.cu
apex/contrib/csrc/optimizers/multi_tensor_distopt_lamb.cpp
apex/contrib/nccl_allocator/__init__.py
apex/contrib/nccl_allocator/nccl_allocator.py
apex/contrib/optimizers/distributed_fused_adam.py
apex/contrib/optimizers/distributed_fused_lamb.py
apex/contrib/test/optimizers/test_dist_adam.py
apex/contrib/test/optimizers/test_distributed_fused_lamb.py
csrc/multi_tensor_apply.cuh
setup.py

Porting distributed Fused Adam and Distributed Fused LAMB
Commits : 
https://github.com/ROCm/apex/commit/6fd8b50f5c913765a060c1628ead47049a1f7d4c
https://github.com/ROCm/apex/commit/ccb59d6885585e48b253278808a16fb6aea19990

Porting dfa and dfl

---

setup.py

This is to exclude nccl_allocator feature for Apex tip (master) 
This solved the issue : https://ontrack-internal.amd.com/browse/SWDEV-523424

Building nccl_allocator only for pytorch 2.6 branch

---

setup.py

This is to exclude nccl_allocator feature for Apex tip (master)
This solved the issue : https://ontrack-internal.amd.com/browse/SWDEV-523424

Building nccl_allocator only for pytorch 2.6 branch (#189)

---

setup.py

Update the condition for building the NCCL allocator, PyTorch should be greater than or equal to 2.6

update condition for building nccl_allocator extension

---

requirements.txt

The error:
File "/tmp/easy_install-_pfhn8pn/matplotlib-3.5.1/.eggs/setuptools_scm-8.3.1-py3.12.egg/setuptools_scm/_integration/pyproject_reading.py", line 36, in read_pyproject section = defn.get("tool", {})[tool_name] ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^ KeyError: 'setuptools_scm'
Solution : https://github.com/matplotlib/matplotlib/blob/v3.8.x/pyproject.toml#L22 matplotlib 3.8 is th e first version to have pyproject.toml with this tool.setuptools_scm section. This higher version of setuptools expects this structure in the Python packages it installs. Matplotlib 3.5.1 doesn't satisfy this condition. The solution is to change the condition to matplotlib>=3.8.

upgrade matplotlib to resolve setuptools_scm error.

---

apex/normalization/fused_layer_norm.py
csrc/layer_norm_cuda.cpp
csrc/layer_norm_cuda_kernel.cu
csrc/static_switch.h
tests/L0/run_fused_layer_norm/test_fused_layer_norm.py

The intra-warp reductions code inside cuWelfordMuSigma2() function in layer norm kernel assumes a warp size of 32, so added a condition for rocm to support gpu warp size (based on earlier apex code). For rocm, adjust the threadsize, based on earlier apex code.
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-484456

Update fused layer norm code from upstream apex repo 

---

apex/normalization/fused_layer_norm.py
csrc/layer_norm_cuda.cpp
csrc/layer_norm_cuda_kernel.cu
csrc/static_switch.h
tests/L0/run_fused_layer_norm/test_fused_layer_norm.py

The intra-warp reductions code inside cuWelfordMuSigma2() function in layer norm kernel assumes a warp size of 32, so added a condition for rocm to support gpu warp size (based on earlier apex code). For rocm, adjust the threadsize, based on earlier apex code.
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-484456

Update fused layer norm code from upstream apex repo. 

---

apex/fused_dense/fused_dense.py
tests/L0/run_mlp/test_mlp.py
tests/L0/run_test.py

- Fix fused_dense_gelu_dense, change the names of the parameters so that they can be accessed by the test appropriately
- Update the absolute tolerances from 0 and 1e-7 to 1e-5
- Changed the order of the tests so that the fused dense and transformer run without errors
Fixes - https://ontrack-internal.amd.com/browse/SWDEV-531206 and https://ontrack-internal.amd.com/browse/SWDEV-531206

Fix fused dense, mlp and transformer unit tests

---

apex/amp/_process_optimizer.py
apex/amp/scaler.py
apex/fused_dense/fused_dense.py
tests/L0/run_amp/test_add_param_group.py
tests/L0/run_amp/test_checkpointing.py
tests/L0/run_amp/test_fused_sgd.py
tests/L0/run_amp/test_larc.py
tests/L0/run_amp/test_multi_tensor_axpby.py
tests/L0/run_amp/test_multi_tensor_l2norm.py
tests/L0/run_amp/test_multi_tensor_scale.py
tests/L0/run_amp/test_multiple_models_optimizers_losses.py
tests/L0/run_amp/utils.py
tests/L0/run_mlp/test_mlp.py
tests/L0/run_transformer/test_batch_sampler.py

- Fix fused dense gelu dense by correcting the name of the parameters so that they match the unit test.
After the above change, fused dense and transformer unit pass when running individually.
But fail when amp unit test are run before these.
- The majority of the unit test failures in transformer and fused dense were caused by not deactivating amp_state handle. So added amp_state deactivation code to run_amp unit tests. 
- The tolerances for mlp unit tests were too low(either 0 or 1e-7). 
- The transformer unit test used cuda as torch default device (due to run_amp) so it had to be explicitly reset to cpu so that the generator for data loader would use cuda.
- Reduced warnings in amp unit tests by updating method for setting device, tensor dtype and overflow buffer creation.

Fix unit tests for transformer, fused dense, mlp

---

apex/amp/_process_optimizer.py
apex/amp/scaler.py
apex/fused_dense/fused_dense.py
tests/L0/run_amp/test_add_param_group.py
tests/L0/run_amp/test_checkpointing.py
tests/L0/run_amp/test_fused_sgd.py
tests/L0/run_amp/test_larc.py
tests/L0/run_amp/test_multi_tensor_axpby.py
tests/L0/run_amp/test_multi_tensor_l2norm.py
tests/L0/run_amp/test_multi_tensor_scale.py
tests/L0/run_amp/test_multiple_models_optimizers_losses.py
tests/L0/run_amp/utils.py
tests/L0/run_mlp/test_mlp.py
tests/L0/run_transformer/test_batch_sampler.py

Fused dense and transformer unit pass when running individually.
But fail when amp unit test are run before these.
- Fix fused dense gelu dense by correcting the name of the parameters so that they match the unit test.
- The majority of the unit test failures in transformer and fused dense were caused by not deactivating amp_state handle. So added amp_state deactivation code to run_amp unit tests. 
- The tolerances for mlp unit tests were too low(either 0 or 1e-7). 
- The transformer unit test used cuda as torch default device (due to run_amp) so it had to be explicitly reset to cpu so that the generator for data loader would use cuda.
- Reduced warnings by updating method for setting device, tensor dtype and overflow buffer creation.

Fix unit tests for transformer, fused dense, mlp (#218)

---

apex/contrib/csrc/groupbn/nhwc_batch_norm_kernel.h

In ROCm 7.0, the warpSize variable is no longer constexpr. This commit replaces the variable use with the correct values based on the architecture we're running on

Do not use warpSize as a constexpr in nhwc_batch_norm_kernel.h

---

.gitmodules
apex/transformer/functional/fused_rope.py
requirements.txt
setup.py
tests/L0/run_transformer/test_fused_rope.py

Added AITER support in fused_rope.py for all 4 variants. Updated fused rope test, reduced tolerances according to unit test in aiter repo.
Tested UT -  python tests/L0/run_transformer/test_fused_rope.py
Added aiter as a submodule and build it in setup.py if it is rocm.
For rocm, it uses AITER backend
For cuda, it uses apex native kernels
Tested with 6.5_internal_testing and upstream main
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-496182

[master] Added AITER as a submodule and use in fused_rope.py 

---

csrc/megatron/scaled_masked_softmax.h
csrc/megatron/scaled_upper_triang_masked_softmax.h

Replacing c10_warp_size with platform based warp_size values
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-541725

Fix fused softmax UT

---

apex/contrib/csrc/groupbn/nhwc_batch_norm_kernel.h

In ROCm 7.0, the warpSize variable is no longer constexpr. This commit replaces the variable use with the correct values based on the architecture we're running on.
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-541770
Tested with Docker : 
`registry-sc-harbor.amd.com/framework/compute-rocm-dkms-no-npi-hipclang:16381_ubuntu24.04_py3.12_pytorch_lw_release-2.6_803962f1`
Updated `/opt/rocm-7.0.0/lib/llvm/bin/../../../include/rocrand/rocrand_mtgp32.h` with the changes in the PR  https://github.com/ROCm/rocm-libraries/pull/507/files 
Checked the following UTs, and these pass:
```
python apex/contrib/test/groupbn/test_groupbn.py 
python apex/contrib/test/groupbn/test_groupbn_channel_last.py 
```

[release/1.6.0] Do not use warpSize as a constexpr in nhwc_batch_norm_kernel.h

---

apex/contrib/csrc/groupbn/nhwc_batch_norm_kernel.h

In ROCm 7.0, the warpSize variable is no longer constexpr. This commit replaces the variable use with the correct values based on the architecture we're running on
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-541770 
Tested with Docker : 
`registry-sc-harbor.amd.com/framework/compute-rocm-dkms-no-npi-hipclang:16196_ubuntu22.04_py3.11_pytorch_lw_release-2.4_3323179f`
> cd /var/lib/jenkins/pytorch 
> git submodule update --init –recursive  
> python tools/amd_build/build_amd.py  
> python setup.py install 
Checked the following UTs, and these pass:
```
python apex/contrib/test/groupbn/test_groupbn.py 
python apex/contrib/test/groupbn/test_groupbn_channel_last.py 
```

[release/1.4.0] Do not use warpSize as a constexpr in nhwc_batch_norm_kernel.h 

---

csrc/megatron/scaled_masked_softmax.h
csrc/megatron/scaled_upper_triang_masked_softmax.h

Replacing c10_warp_size and platform based warp_size values with at::cuda::warp_size() values
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-541725

[master] Fix fused softmax ut

---

csrc/megatron/scaled_masked_softmax.h
csrc/megatron/scaled_upper_triang_masked_softmax.h

Cherry-pick of https://github.com/ROCm/apex/pull/237

[AUTOGENERATED] [release/1.6.0] [master] Fix fused softmax ut

---

apex/contrib/csrc/groupbn/nhwc_batch_norm_kernel.h

Replaced warpsize with C10_WARP_SIZE
Tested with docker
registry-sc-harbor.amd.com/framework/compute-rocm-dkms-no-npi-hipclang:16387_ubuntu22.04_py3.10_pytorch_lw_rocm7.0_internal_testing_c3f758e0
Checked the UTs and these pass:
python apex/contrib/test/groupbn/test_groupbn.py 
python apex/contrib/test/groupbn/test_groupbn_channel_last.py 
Fixes: https://ontrack-internal.amd.com/browse/SWDEV-541770

Replaced warpsize with C10_WARP_SIZE

---

apex/contrib/csrc/groupbn/nhwc_batch_norm_kernel.h

Cherry-pick of https://github.com/ROCm/apex/pull/249

[AUTOGENERATED] [release/1.7.0] Replaced warpsize with C10_WARP_SIZE

---

apex/contrib/csrc/groupbn/nhwc_batch_norm_kernel.h

Cherry-pick of https://github.com/ROCm/apex/pull/249

[AUTOGENERATED] [release/1.4.0] Replaced warpsize with C10_WARP_SIZE

---

README.md
apex/transformer/functional/fused_rope.py
setup.py

made a flag to switch on/off aiter compile using --aiter when installing apex
fixes https://ontrack-internal.amd.com/browse/SWDEV-542835 
Tested it on Docker image : 
registry-sc-harbor.amd.com/framework/compute-rocm-dkms-no-npi-hipclang:16387_ubuntu22.04_py3.10_pytorch_lw_rocm7.0_internal_testing_c3f758e0
| Setup.py condition | Is aiter compiled? | Ut condition                  | Backend used | Ut status                        |
| ------------------ | ------------------ | ----------------------------- | ------------ | -------------------------------- |
| \--aiter           | yes                |                               | aiter        | Fail, expected due to llvm issue |
| \--aiter           | yes                | USE_ROCM_AITER_ROPE_BACKEND=0 | Native apex  | pass …

Disabling Aiter Installation in default build

---

apex/contrib/csrc/groupbn/batch_norm.h
apex/contrib/csrc/groupbn/batch_norm_add_relu.h
apex/contrib/csrc/groupbn/nhwc_batch_norm_kernel.h
apex/contrib/csrc/multihead_attn/softmax.cuh
apex/contrib/csrc/transducer/transducer_joint_kernel.cu
apex/contrib/csrc/xentropy/xentropy_kernel.cu
csrc/megatron/fused_rotary_positional_embedding.h
csrc/megatron/generic_scaled_masked_softmax.h
csrc/megatron/scaled_masked_softmax.h
csrc/welford.cu

Replace C10_WARP_SIZE, constant WARP_SIZE, constant THREADS_PER_WARP, warp.*32 regex uses with at::cuda::warp_size() when not used __device__ or __global__.
Tested with docker 
`registry-sc-harbor.amd.com/framework/compute-rocm-dkms-no-npi-hipclang:16420_ubuntu22.04_py3.10_pytorch_lw_rocm7.0_internal_testing_2d567672`
Affected extensions:
1. fused rope - csrc/megatron/fused_rotary_positional_embedding.h
2. scaled_masked_softmax_cuda - , csrc/megatron/scaled_masked_softmax.h
3. generic_scaled_masked_softmax_cuda - csrc/megatron/generic_scaled_masked_softmax.h
4. scaled_upper_triang_masked_softmax_cuda - csrc/megatron/scaled_upper_triang_masked_softmax.h
5. group batch norm - apex/contrib/csrc/groupbn/batch_norm.h, apex/contrib/csrc/groupbn/batch_norm_add_relu.h
6. multihead attention - …

Fix warp size

---

apex/fused_dense/fused_dense.py
tests/L0/run_fused_dense/test_gelu.py

reset parameters for FusedDenseGeluDense similar to FusedDense to make the test_gelu pass
Ran the unit tests:
```
python tests/L0/run_fused_dense/test_gelu.py 
APEX_TEST_WITH_ROCM=1 APEX_SKIP_FLAKY_TEST=1 python run_test.py --include run_fused_dense 
```
tested with docker
`registry-sc-harbor.amd.com/framework/compute-rocm-dkms-no-npi-hipclang:16456_ubuntu22.04_py3.10_pytorch_lw_rocm7.0_internal_testing_3d404259`

Fix test_gelu unit test

---

tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py

update the param_id calculation so that it works on both CPX and SPX modes
These 4 tests failed in MI308 machine because they had virtual GPUs
```
test_learning_pipelining_without_interleaving 
test_learning_pipelining_with_interleaving 
test_learning_async_pipelining_without_interleaving 
test_learning_async_pipelining_with_interleaving 
```
On CPX, local device ids are not laid out in contiguous DP groups. So the computed param_id doesn’t match the stage that initialized the module
So the solution is to use 
` param_id = parallel_state.get_pipeline_model_parallel_rank() + vm_id * pipeline_model_parallel_world_size
` 
The indivigual tests were tested with this 
`python3 tests/L0/run_transformer/test_pipeline_parallel_fwd_bwd.py -k test_learning_async_pipelining_with_interleaving …

[release/1.8.0] update the param_id calculation so that it works on both CPX and SPX modes
