apex/amp/scaler.py
This PR enables python only based install for FP16 training of sparse tensors using dynamic loss scaling..
=> Enable sparse tensor support for python only based Dyn. Loss scaling.

csrc/multi_tensor_apply.cuh
This PR enables dynamic loss scaling support with multi_tensor_apply with sparse tensor support.
=> [Extensions] Enable support for sparse tensors for multi_tensor_apply

setup.py
This is enabled as part of IFU in the last PR.
=> [Extensions] Enable multi tensor apply FusedAdagrad

csrc/multi_tensor_sgd_kernel.cu, tests/L0/run_amp/test_fused_sgd.py, tests/L0/run_amp/test_multiple_models_optimizers_losses.py
This PR is intended to enable the test suits : ```test_fused_sgd``` and ```test_multiple_models_optimizers_losses``` as mentioned in the the comment in the previous PR. 
https://github.com/ROCmSoftwarePlatform/apex/pull/5#issuecomment-629474681
=> [FusedOptimizers] Bug fixes in fused optimizers for fp16/bfp16.

README.md
This PR contains the changes for readme updates - steps and pre-requisites on ROCm.
=> [Documentation] Update the readme for ROCm.

apex/amp/compat.py, apex/amp/lists/tensor_overrides.py, apex/contrib/csrc/multihead_attn/softmax.h, apex/contrib/sparsity/README.md, apex/contrib/sparsity/__init__.py, apex/contrib/sparsity/asp.py, apex/contrib/sparsity/sparse_masklib.py, apex/contrib/sparsity/test/checkpointing_test_part1.py, apex/contrib/sparsity/test/checkpointing_test_part2.py, apex/contrib/sparsity/test/checkpointing_test_reference.py, apex/contrib/sparsity/test/toy_problem.py, apex/parallel/optimized_sync_batchnorm_kernel.py, csrc/syncbn.cpp, csrc/welford.cu, tests/L0/run_optimizers/test_lamb.py, tests/distributed/synced_batchnorm/single_gpu_unit_test.py, tests/distributed/synced_batchnorm/two_gpu_test_different_batch_size.py, tests/distributed/synced_batchnorm/two_gpu_unit_test.py, tests/distributed/synced_batchnorm/unit_test.sh
IFU : 07/07/2020
This IFU is needed to enable new operators.
=> IFU-07072020

tests/distributed/run_rocm_distributed.sh
This test will be enabled again in future release.
=> Skip mgpu bfloat16 tests.

csrc/mlp.cpp, csrc/mlp_cuda.cu, setup.py, tests/L0/run_mlp/test_mlp.py, tests/L0/run_test.py
* This PR enables mlp_cuda extension.
* Enabled unit tests for mlp_cuda.
=> Enable mlp_cuda extension.

setup.py
This PR supports deprecated FusedAdam and deprecated FusedLAMB
=> [contrib] Support optimizers on rocm. 

apex/contrib/csrc/xentropy/xentropy_kernel.cu, setup.py
This PR supports xentropy extension for apex
=> [contrib] Support for xentropy extension. 

tests/L0/run_amp/test_multi_tensor_axpby.py, tests/L0/run_amp/test_multi_tensor_scale.py, tests/L0/run_optimizers/test_adagrad.py, tests/L0/run_optimizers/test_adam.py
Skipping unit tests for stability of CI.
=> Skip the unit tests

csrc/welford.cu, tests/distributed/synced_batchnorm/python_single_gpu_unit_test.py, tests/distributed/synced_batchnorm/single_gpu_unit_test.py, tests/distributed/synced_batchnorm/test_groups.py, tests/distributed/synced_batchnorm/two_gpu_unit_test.py, tests/distributed/synced_batchnorm/unit_test.sh
- incorrect use of __shfl_down
- fix warp size assumptions
- update unit tests to exit on failure
=> fix bugs in syncbn

apex/contrib/csrc/optimizers/fused_adam_cuda_kernel.cu, apex/contrib/csrc/optimizers/fused_lamb_cuda_kernel.cu, csrc/multi_tensor_adagrad.cu, csrc/multi_tensor_adam.cu, csrc/multi_tensor_apply.cuh, csrc/multi_tensor_axpby_kernel.cu, csrc/multi_tensor_l2norm_kernel.cu, csrc/multi_tensor_lamb.cu, csrc/multi_tensor_lamb_stage_1.cu, csrc/multi_tensor_lamb_stage_2.cu, csrc/multi_tensor_novograd.cu, csrc/multi_tensor_scale_kernel.cu, csrc/multi_tensor_sgd_kernel.cu
This reverts commit bdd481d15da054bceecd1ea61fe9c45e148f71b6.
=> Revert "pass all TensorListMetadata as pointer to pinned host memory (#13)

apex/contrib/csrc/optimizers/multi_tensor_distopt_lamb.cpp, apex/contrib/csrc/optimizers/multi_tensor_distopt_lamb_kernel.cu, apex/contrib/optimizers/distributed_fused_lamb.py
Enable distributed FusedLAMB in apex/contrib.
Command used to build:
python setup.py install --cpp_ext --cuda_ext --distributed_adam --xentropy --deprecated_fused_adam --distributed_lamb --fast_multihead_attn 2>&1 | tee ../apex_build_mha.log
=> Enable Distributed FusedLAMB

apex/contrib/csrc/multihead_attn/encdec_multihead_attn_cuda.cu, apex/contrib/csrc/multihead_attn/encdec_multihead_attn_norm_add_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_additive_mask_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_norm_add_cuda.cu, apex/contrib/csrc/multihead_attn/strided_batched_gemm.h
Updated all the files in MHA with rocblas_alt_impl flag in bwd rocblas calls. Checked all the unit tests and all of them passed.
=> Add rocblas_alt_impl falg for bwd rocblas calls in MHA

apex/contrib/csrc/multihead_attn/encdec_multihead_attn_cuda.cu, apex/contrib/csrc/multihead_attn/encdec_multihead_attn_norm_add_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_additive_mask_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_norm_add_cuda.cu, apex/contrib/csrc/multihead_attn/strided_batched_gemm.cuh, csrc/fused_dense_cuda.cu, csrc/mlp_cuda.cu
Changes are migrated from original pytorch PR - https://github.com/pytorch/pytorch/pull/105881
=> Changes to support hipblas migration

apex/contrib/csrc/multihead_attn/encdec_multihead_attn_cuda.cu, apex/contrib/csrc/multihead_attn/encdec_multihead_attn_norm_add_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_additive_mask_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_bias_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_cuda.cu, apex/contrib/csrc/multihead_attn/self_multihead_attn_norm_add_cuda.cu, apex/contrib/csrc/multihead_attn/strided_batched_gemm.cuh, csrc/fused_dense_cuda.cu, csrc/mlp_cuda.cu
This reverts commit 8fc9b21fed40d458a6088bbb31501bef2db8c749.
=> Revert "Changes to support hipblas migration (#113)"

setup.py
Fixes SWDEV-495716 and SWDEV-495670
=> Updated setup.py to fix indent issue

apex/transformer/functional/__init__.py, apex/transformer/functional/fused_rope.py, csrc/megatron/fused_rotary_positional_embedding.cpp, csrc/megatron/fused_rotary_positional_embedding.h, csrc/megatron/fused_rotary_positional_embedding_cuda.cu, setup.py, tests/L0/run_transformer/test_fused_rope.py
Cherry-pick some commits about fused RoPE
=> Fused RoPE

apex/transformer/parallel_state.py
creating a setter for the global variable
=> add setter for virtual world size (#1541)

apex/_autocast_utils.py, apex/mlp/mlp.py
Fixed based on Nvidia commit https://github.com/NVIDIA/apex/commit/81c9aca6405669cef6bd60b5b3e121cc79d0b6db
=> Replaced amp function with autocast in mlp class

tests/L0/run_fp16util/test_fp16util.py
=> Making fp16_utils tests run

csrc/fused_dense_cuda.cu, setup.py
Call HipblasLT api based upon torch backend
=> HipblasLT runtime

apex/fused_dense/fused_dense.py
update fused_dense to use torch.autocast instead of apex amp Based on https://github.com/NVIDIA/apex/commit/1d7711100bb58dc761a2fad89f30d41239450f58
* update fused_dense to use torch.autocast instead of apex amp
* use _cast_if_autocast_enabled for inputs
=> Replaced amp function with torch autocast

apex/transformer/amp/grad_scaler.py
Added unscale_grads to transformer Grad scaler
Reference Nvidia : https://github.com/NVIDIA/apex/commit/da9f5ae998ee32a5b02c308e5c868111390dc661
=> Feature transformer unscale grads

apex/contrib/csrc/focal_loss/focal_loss_cuda.cpp
reference Commit from Nvidia 
- https://github.com/ROCm/apex/commit/0145d69de5ca3554ddbce5530345f3c6073d97c8
- https://github.com/ROCm/apex/commit/23c1f86520e22b505e8fdfcf6298273dff2d93d8
=> Added torch check and release GIL in focal loss

apex/contrib/csrc/index_mul_2d/index_mul_2d_cuda.cpp
Ref commit Nvidia - https://github.com/NVIDIA/apex/commit/0145d69de5ca3554ddbce5530345f3c6073d97c8
and https://github.com/NVIDIA/apex/commit/23c1f86520e22b505e8fdfcf6298273dff2d93d8
=> Added torch check and release GIL in index_mul_2d

apex/contrib/csrc/transducer/transducer_loss.cpp, apex/contrib/test/transducer/test_transducer_joint.py, setup.py
Nvidia Commit Ref: https://github.com/NVIDIA/apex/commit/23c1f86520e22b505e8fdfcf6298273dff2d93d8
Transducers - Release GIL in and remove two skip statements for two tests that used to fail in earlier version and pass in current version
Add missing function in setup.py - useful when installing contrib modules
=> Added Release GIL, removed 2 skip statement for UT 

tests/L0/run_transformer/test_fused_rope.py
Reduced tolerance to tolerance to 1e-3 to pass for f16 and bf16 cases
=> Reduced tolerance for lower precision data f16 and bf16.

apex/transformer/testing/distributed_test_base.py, csrc/megatron/fused_weight_gradient_dense.cpp, csrc/megatron/fused_weight_gradient_dense_16bit_prec_cuda.cu, csrc/megatron/fused_weight_gradient_dense_cuda.cu, setup.py
Fused Gradient Accumulation is now available in apex in releases 1.5.0 and 1.6.0 and main (1.7.0)
Will have to optimize for precision and time taken by replacing cublasGemmEx with cublasLtMatmul similar to csrc/fused_dense_cuda.cu
=> Feature fused gradient accum 

apex/transformer/testing/distributed_test_base.py, csrc/megatron/fused_weight_gradient_dense.cpp, csrc/megatron/fused_weight_gradient_dense_16bit_prec_cuda.cu, csrc/megatron/fused_weight_gradient_dense_cuda.cu, setup.py
Providing Fused Gradient Accumation feature in apex by adding fused_weight_gradient_mlp_cuda module in setup.py.
=> Feature fused gradient accum

apex/transformer/testing/distributed_test_base.py, csrc/megatron/fused_weight_gradient_dense.cpp, csrc/megatron/fused_weight_gradient_dense_16bit_prec_cuda.cu, csrc/megatron/fused_weight_gradient_dense_cuda.cu, setup.py
* Added feature fused_gradient_accumulator
* Added args in to _run
Providing Fused Gradient Accumation feature in apex by adding fused_weight_gradient_mlp_cuda module in setup.py.
=> Feature fused gradient accum  (#164)

csrc/megatron/fused_weight_gradient_dense_16bit_prec_cuda.cu, csrc/megatron/fused_weight_gradient_dense_cuda.cu
=> Altered the HIPBLAS to CUBLAS

csrc/megatron/fused_bias_swiglu.cpp, csrc/megatron/fused_bias_swiglu_cuda.cu, setup.py, tests/L0/run_transformer/test_fused_bias_swiglu.py
Added fused_bias_swiglu kernel function and the test cases to test the different datatypes for forward and backward
=> Added fused_bias_swiglu kernel function 

csrc/megatron/fused_bias_swiglu.cpp, csrc/megatron/fused_bias_swiglu_cuda.cu, setup.py, tests/L0/run_transformer/test_fused_bias_swiglu.py
Added fused_bias_swiglu kernel function and the test cases to test the different datatypes for forward and backward
=> Added fused_bias_swiglu kernel function

apex/contrib/csrc/optimizers/multi_tensor_distopt_lamb.cpp, apex/contrib/optimizers/distributed_fused_lamb.py, apex/contrib/test/optimizers/test_distributed_fused_lamb.py
Add support for parameters - fused_norm, full_ar, set_param_views_to_flat_buffer, skip_allgather, fuse_scale, param_order, Nccl_allgather_channels
Related Ticket : https://ontrack-internal.amd.com/browse/SWDEV-519863
=> Ported distributed fused lamb from upstream repo. 

tests/L0/run_rocm.sh
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-527387 
Included run_transformer UTs into run_rocm.sh
=> Include run_transformer UTs in the run_rocm.sh file

csrc/megatron/fused_weight_gradient_dense_16bit_prec_cuda.cu, csrc/megatron/fused_weight_gradient_dense_cuda.cu
Currently workspace of hipblaslt is allocated by hipMalloc and freed by hipFree. It has about ~1ms overhead. 
It's a better way to allocate memory through at::empty the torch allocator will help us to manage device memory and avoid calls of hip runtime api.
hipMalloc
hipFree
=> [ROCm] Use at::empty to manage workspace memory to avoid hip runtime calls

csrc/megatron/fused_weight_gradient_dense_16bit_prec_cuda.cu, csrc/megatron/fused_weight_gradient_dense_cuda.cu
Optimize the memory for fused_weight_gradient_mlp_cuda module
cherry picked : 667af654f73d4aea00657659bfefcf95e725898b
related PR : https://github.com/ROCm/apex/pull/197
=> [ROCm] Use at::empty to manage workspace memory to avoid hip runtime calls (#197)

apex/contrib/optimizers/distributed_fused_adam.py
Update distributed fused adam, integrate Pipeline reduce-scatter, all-reduce and support grad dtype != param dtype
Integrate two commits to apex/contrib/optimizers/distributed_fused_adam.py
https://github.com/NVIDIA/apex/commit/2eb64daebeca9048a6e2c42fafceeaedd4e310d2
https://github.com/NVIDIA/apex/commit/b9d758c0c8b354b014c4d4c3a5c56d708b776de3
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-502615
=> Update distributed fused adam - integrate Pipeline operations and support different grad 

setup.py
=> Revert "update condition for building nccl_allocator extension"

tests/L0/run_amp/test_add_param_group.py, tests/L0/run_amp/test_basic_casts.py, tests/L0/run_amp/test_cache.py, tests/L0/run_amp/test_larc.py, tests/L0/run_amp/test_multi_tensor_axpby.py, tests/L0/run_amp/test_multi_tensor_l2norm.py, tests/L0/run_amp/test_multi_tensor_scale.py, tests/L0/run_amp/test_multiple_models_optimizers_losses.py, tests/L0/run_amp/test_promotion.py, tests/L0/run_amp/test_rnn.py, tests/L0/run_amp/utils.py, tests/L0/run_transformer/test_batch_sampler.py
Fixes : https://ontrack-internal.amd.com/browse/SWDEV-523467
=> Reset torch default device to cpu after running the amp unit tests.

csrc/megatron/scaled_masked_softmax.h, csrc/megatron/scaled_upper_triang_masked_softmax.h
Cherry-pick of https://github.com/ROCm/apex/pull/228
=> [AUTOGENERATED] [release/1.6.0] [master] Fix fused softmax UT

csrc/megatron/scaled_masked_softmax.h, csrc/megatron/scaled_upper_triang_masked_softmax.h
Cherry-pick of https://github.com/ROCm/apex/pull/228
=> [AUTOGENERATED] [release/1.5.0] [master] Fix fused softmax UT

csrc/megatron/scaled_masked_softmax.h, csrc/megatron/scaled_upper_triang_masked_softmax.h
Cherry-pick of https://github.com/ROCm/apex/pull/237
=> [AUTOGENERATED] [release/1.7.0] [master] Fix fused softmax ut

tests/test_extension_import.py
correct the approach to get to the apex folder from the test file
=> [master] fix the folder error in import extension test

apex/contrib/csrc/transducer/transducer_joint_kernel.cu
Cherry-pick of https://github.com/ROCm/apex/pull/264
=> [AUTOGENERATED] [release/1.7.0] Fix build error

apex/contrib/csrc/transducer/transducer_joint_kernel.cu
Cherry-pick of https://github.com/ROCm/apex/pull/264
=> [AUTOGENERATED] [release/1.6.0] Fix build error

apex/contrib/csrc/transducer/transducer_joint_kernel.cu
Cherry-pick of https://github.com/ROCm/apex/pull/264
=> [AUTOGENERATED] [release/1.4.0] Fix build error
